# Generated by Django 5.2.3 on 2025-07-10 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_contact',
            new_name='Contact',
        ),
        migrations.RenameModel(
            old_name='Blog_post',
            new_name='Post',
        ),
    ]
