# Generated by Django 5.2.3 on 2025-07-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('country', models.CharField(default=500)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
