# Generated by Django 5.2.3 on 2025-07-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_signup_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
    ]
