# Generated by Django 5.2.3 on 2025-07-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_alter_signup_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
